package com.e7orbit.ui

import androidx.annotation.DrawableRes
import com.e7orbit.R

// Generated by tools/sync_gear_icons.py from equip_item_zl.db.
@DrawableRes
internal fun exactGearItemIconRes(code: String): Int? = when (code.take(4)) {
    "eah2" -> gearItemIcon_eah2(code)
    "eah3" -> gearItemIcon_eah3(code)
    "ear1" -> gearItemIcon_ear1(code)
    "ear2" -> gearItemIcon_ear2(code)
    "ear3" -> gearItemIcon_ear3(code)
    "ear4" -> gearItemIcon_ear4(code)
    "ear5" -> gearItemIcon_ear5(code)
    "ecb6" -> gearItemIcon_ecb6(code)
    "ecd6" -> gearItemIcon_ecd6(code)
    "ecep" -> gearItemIcon_ecep(code)
    "ecg6" -> gearItemIcon_ecg6(code)
    "ecl2" -> gearItemIcon_ecl2(code)
    "ecn2" -> gearItemIcon_ecn2(code)
    "econ" -> gearItemIcon_econ(code)
    "ecp6" -> gearItemIcon_ecp6(code)
    "ecp7" -> gearItemIcon_ecp7(code)
    "ecq6" -> gearItemIcon_ecq6(code)
    "ecs1" -> gearItemIcon_ecs1(code)
    "ecs2" -> gearItemIcon_ecs2(code)
    "ecw6" -> gearItemIcon_ecw6(code)
    "edb6" -> gearItemIcon_edb6(code)
    "edd6" -> gearItemIcon_edd6(code)
    "edg6" -> gearItemIcon_edg6(code)
    "edp6" -> gearItemIcon_edp6(code)
    "edq6" -> gearItemIcon_edq6(code)
    "edw6" -> gearItemIcon_edw6(code)
    "eep2" -> gearItemIcon_eep2(code)
    "eep3" -> gearItemIcon_eep3(code)
    "eep_" -> gearItemIcon_eep_(code)
    "eff1" -> gearItemIcon_eff1(code)
    "egn2" -> gearItemIcon_egn2(code)
    "ela1" -> gearItemIcon_ela1(code)
    "ela8" -> gearItemIcon_ela8(code)
    "ela9" -> gearItemIcon_ela9(code)
    "elre" -> gearItemIcon_elre(code)
    "emp1" -> gearItemIcon_emp1(code)
    "emp2" -> gearItemIcon_emp2(code)
    "emp3" -> gearItemIcon_emp3(code)
    "emp4" -> gearItemIcon_emp4(code)
    "emp5" -> gearItemIcon_emp5(code)
    "emp6" -> gearItemIcon_emp6(code)
    "emp7" -> gearItemIcon_emp7(code)
    "emp8" -> gearItemIcon_emp8(code)
    "emp9" -> gearItemIcon_emp9(code)
    "ems2" -> gearItemIcon_ems2(code)
    "eorb" -> gearItemIcon_eorb(code)
    "erp1" -> gearItemIcon_erp1(code)
    "erp2" -> gearItemIcon_erp2(code)
    "erp3" -> gearItemIcon_erp3(code)
    "erp4" -> gearItemIcon_erp4(code)
    "esc0" -> gearItemIcon_esc0(code)
    "ese1" -> gearItemIcon_ese1(code)
    "esh1" -> gearItemIcon_esh1(code)
    "esh2" -> gearItemIcon_esh2(code)
    "esh3" -> gearItemIcon_esh3(code)
    "espb" -> gearItemIcon_espb(code)
    "espd" -> gearItemIcon_espd(code)
    "espg" -> gearItemIcon_espg(code)
    "espp" -> gearItemIcon_espp(code)
    "espq" -> gearItemIcon_espq(code)
    "espw" -> gearItemIcon_espw(code)
    "ess1" -> gearItemIcon_ess1(code)
    "ete1" -> gearItemIcon_ete1(code)
    "ewb3" -> gearItemIcon_ewb3(code)
    "ewc2" -> gearItemIcon_ewc2(code)
    "ezl1" -> gearItemIcon_ezl1(code)
    "ezl2" -> gearItemIcon_ezl2(code)
    "ezl3" -> gearItemIcon_ezl3(code)
    "ezl4" -> gearItemIcon_ezl4(code)
    "ezl5" -> gearItemIcon_ezl5(code)
    "ezl8" -> gearItemIcon_ezl8(code)
    "ezl9" -> gearItemIcon_ezl9(code)
    else -> null
}

@DrawableRes
private fun gearItemIcon_eah2(code: String): Int? = when (code) {
    "eah22a",
    -> R.drawable.e7_item_icon_eq_armor_arena017
    "eah23a",
    -> R.drawable.e7_item_icon_eq_armor_arena018
    "eah24a",
    -> R.drawable.e7_item_icon_eq_armor_arena019
    "eah25a",
    -> R.drawable.e7_item_icon_eq_armor_arena020
    "eah26a",
    -> R.drawable.e7_item_icon_eq_armor_arena021
    "eah27a",
    -> R.drawable.e7_item_icon_eq_armor_arena022
    "eah28a",
    -> R.drawable.e7_item_icon_eq_armor_arena023
    "eah29a",
    -> R.drawable.e7_item_icon_eq_armor_arena024
    "eah22b",
    -> R.drawable.e7_item_icon_eq_boot_arena017
    "eah23b",
    -> R.drawable.e7_item_icon_eq_boot_arena018
    "eah24b",
    -> R.drawable.e7_item_icon_eq_boot_arena019
    "eah25b",
    -> R.drawable.e7_item_icon_eq_boot_arena020
    "eah26b",
    -> R.drawable.e7_item_icon_eq_boot_arena021
    "eah27b",
    -> R.drawable.e7_item_icon_eq_boot_arena022
    "eah28b",
    -> R.drawable.e7_item_icon_eq_boot_arena023
    "eah29b",
    -> R.drawable.e7_item_icon_eq_boot_arena024
    "eah22h",
    -> R.drawable.e7_item_icon_eq_helm_arena017
    "eah23h",
    -> R.drawable.e7_item_icon_eq_helm_arena018
    "eah24h",
    -> R.drawable.e7_item_icon_eq_helm_arena019
    "eah25h",
    -> R.drawable.e7_item_icon_eq_helm_arena020
    "eah26h",
    -> R.drawable.e7_item_icon_eq_helm_arena021
    "eah27h",
    -> R.drawable.e7_item_icon_eq_helm_arena022
    "eah28h",
    -> R.drawable.e7_item_icon_eq_helm_arena023
    "eah29h",
    -> R.drawable.e7_item_icon_eq_helmet_arena024
    "eah22n",
    -> R.drawable.e7_item_icon_eq_neck_arena017
    "eah23n",
    -> R.drawable.e7_item_icon_eq_neck_arena018
    "eah24n",
    -> R.drawable.e7_item_icon_eq_neck_arena019
    "eah25n",
    -> R.drawable.e7_item_icon_eq_neck_arena020
    "eah26n",
    -> R.drawable.e7_item_icon_eq_neck_arena021
    "eah27n",
    -> R.drawable.e7_item_icon_eq_neck_arena022
    "eah28n",
    -> R.drawable.e7_item_icon_eq_neck_arena023
    "eah29n",
    -> R.drawable.e7_item_icon_eq_neck_arena024
    "eah22r",
    -> R.drawable.e7_item_icon_eq_ring_arena017
    "eah23r",
    -> R.drawable.e7_item_icon_eq_ring_arena018
    "eah24r",
    -> R.drawable.e7_item_icon_eq_ring_arena019
    "eah25r",
    -> R.drawable.e7_item_icon_eq_ring_arena020
    "eah26r",
    -> R.drawable.e7_item_icon_eq_ring_arena021
    "eah27r",
    -> R.drawable.e7_item_icon_eq_ring_arena022
    "eah28r",
    -> R.drawable.e7_item_icon_eq_ring_arena023
    "eah29r",
    -> R.drawable.e7_item_icon_eq_ring_arena024
    "eah22w",
    -> R.drawable.e7_item_icon_eq_weapon_arena017
    "eah23w",
    -> R.drawable.e7_item_icon_eq_weapon_arena018
    "eah24w",
    -> R.drawable.e7_item_icon_eq_weapon_arena019
    "eah25w",
    -> R.drawable.e7_item_icon_eq_weapon_arena020
    "eah26w",
    -> R.drawable.e7_item_icon_eq_weapon_arena021
    "eah27w",
    -> R.drawable.e7_item_icon_eq_weapon_arena022
    "eah28w",
    -> R.drawable.e7_item_icon_eq_weapon_arena023
    "eah29w",
    -> R.drawable.e7_item_icon_eq_weapon_arena024
    else -> null
}

@DrawableRes
private fun gearItemIcon_eah3(code: String): Int? = when (code) {
    "eah30a",
    -> R.drawable.e7_item_icon_eq_armor_arena025
    "eah31a",
    -> R.drawable.e7_item_icon_eq_armor_arena026
    "eah32a",
    -> R.drawable.e7_item_icon_eq_armor_arena027
    "eah30b",
    -> R.drawable.e7_item_icon_eq_boot_arena025
    "eah31b",
    -> R.drawable.e7_item_icon_eq_boot_arena026
    "eah32b",
    -> R.drawable.e7_item_icon_eq_boot_arena027
    "eah32h",
    -> R.drawable.e7_item_icon_eq_helm_arena027
    "eah30h",
    -> R.drawable.e7_item_icon_eq_helmet_arena025
    "eah31h",
    -> R.drawable.e7_item_icon_eq_helmet_arena026
    "eah30n",
    -> R.drawable.e7_item_icon_eq_neck_arena025
    "eah31n",
    -> R.drawable.e7_item_icon_eq_neck_arena026
    "eah32n",
    -> R.drawable.e7_item_icon_eq_neck_arena027
    "eah30r",
    -> R.drawable.e7_item_icon_eq_ring_arena025
    "eah31r",
    -> R.drawable.e7_item_icon_eq_ring_arena026
    "eah32r",
    -> R.drawable.e7_item_icon_eq_ring_arena027
    "eah30w",
    -> R.drawable.e7_item_icon_eq_weapon_arena025
    "eah31w",
    -> R.drawable.e7_item_icon_eq_weapon_arena026
    "eah32w",
    -> R.drawable.e7_item_icon_eq_weapon_arena027
    else -> null
}

@DrawableRes
private fun gearItemIcon_ear1(code: String): Int? = when (code) {
    "ear1_a",
    -> R.drawable.e7_item_icon_eq_armor_armory
    "ear1_b",
    -> R.drawable.e7_item_icon_eq_boot_armory
    "ear1_h",
    -> R.drawable.e7_item_icon_eq_helm_armory
    "ear1_n",
    -> R.drawable.e7_item_icon_eq_neck_armory
    "ear1_r",
    -> R.drawable.e7_item_icon_eq_ring_armory
    "ear1_w",
    -> R.drawable.e7_item_icon_eq_weapon_armory
    else -> null
}

@DrawableRes
private fun gearItemIcon_ear2(code: String): Int? = when (code) {
    "ear2_a",
    -> R.drawable.e7_item_icon_eq_armor_armory
    "ear2_b",
    -> R.drawable.e7_item_icon_eq_boot_armory
    "ear2_h",
    -> R.drawable.e7_item_icon_eq_helm_armory
    "ear2_w",
    -> R.drawable.e7_item_icon_eq_weapon_armory
    else -> null
}

@DrawableRes
private fun gearItemIcon_ear3(code: String): Int? = when (code) {
    "ear3_a",
    -> R.drawable.e7_item_icon_eq_armor_armory
    "ear3_b",
    -> R.drawable.e7_item_icon_eq_boot_armory
    "ear3_h",
    -> R.drawable.e7_item_icon_eq_helm_armory
    "ear3_w",
    -> R.drawable.e7_item_icon_eq_weapon_armory
    else -> null
}

@DrawableRes
private fun gearItemIcon_ear4(code: String): Int? = when (code) {
    "ear4_b",
    -> R.drawable.e7_item_icon_eq_boot_armory
    else -> null
}

@DrawableRes
private fun gearItemIcon_ear5(code: String): Int? = when (code) {
    "ear5_b",
    -> R.drawable.e7_item_icon_eq_boot_armory
    else -> null
}

@DrawableRes
private fun gearItemIcon_ecb6(code: String): Int? = when (code) {
    "ecb6a",
    "ecb6a_chaos",
    "ecb6a_craft",
    "ecb6a_craft_chaos",
    -> R.drawable.e7_item_icon_eq_armor_orb006
    "ecb6a_chaos_u",
    "ecb6a_craft_chaos_u",
    "ecb6a_craft_u",
    "ecb6a_u",
    -> R.drawable.e7_item_icon_eq_armor_orb007
    "ecb6b",
    "ecb6b_chaos",
    "ecb6b_craft",
    "ecb6b_craft_chaos",
    -> R.drawable.e7_item_icon_eq_boot_orb006
    "ecb6b_chaos_u",
    "ecb6b_craft_chaos_u",
    "ecb6b_craft_u",
    "ecb6b_u",
    -> R.drawable.e7_item_icon_eq_boot_orb007
    "ecb6h",
    "ecb6h_chaos",
    "ecb6h_craft",
    "ecb6h_craft_chaos",
    -> R.drawable.e7_item_icon_eq_helm_orb006
    "ecb6h_chaos_u",
    "ecb6h_craft_chaos_u",
    "ecb6h_craft_u",
    "ecb6h_u",
    -> R.drawable.e7_item_icon_eq_helm_orb007
    "ecb6n",
    "ecb6n_chaos",
    "ecb6n_craft",
    "ecb6n_craft_chaos",
    -> R.drawable.e7_item_icon_eq_neck_orb006
    "ecb6n_chaos_u",
    "ecb6n_craft_chaos_u",
    "ecb6n_craft_u",
    "ecb6n_u",
    -> R.drawable.e7_item_icon_eq_neck_orb007
    "ecb6r",
    "ecb6r_chaos",
    "ecb6r_craft",
    "ecb6r_craft_chaos",
    -> R.drawable.e7_item_icon_eq_ring_orb106
    "ecb6r_chaos_u",
    "ecb6r_craft_chaos_u",
    "ecb6r_craft_u",
    "ecb6r_u",
    -> R.drawable.e7_item_icon_eq_ring_orb107
    "ecb6w",
    "ecb6w_chaos",
    "ecb6w_craft",
    "ecb6w_craft_chaos",
    -> R.drawable.e7_item_icon_eq_weapon_orb006
    "ecb6w_chaos_u",
    "ecb6w_craft_chaos_u",
    "ecb6w_craft_u",
    "ecb6w_u",
    -> R.drawable.e7_item_icon_eq_weapon_orb007
    else -> null
}

@DrawableRes
private fun gearItemIcon_ecd6(code: String): Int? = when (code) {
    "ecd6a",
    "ecd6a_chaos",
    "ecd6a_craft",
    "ecd6a_craft_chaos",
    -> R.drawable.e7_item_icon_eq_armor_dem006
    "ecd6a_chaos_u",
    "ecd6a_craft_chaos_u",
    "ecd6a_craft_u",
    "ecd6a_u",
    -> R.drawable.e7_item_icon_eq_armor_dem007
    "ecd6b",
    "ecd6b_chaos",
    "ecd6b_craft",
    "ecd6b_craft_chaos",
    -> R.drawable.e7_item_icon_eq_boot_dem006
    "ecd6b_chaos_u",
    "ecd6b_craft_chaos_u",
    "ecd6b_craft_u",
    "ecd6b_u",
    -> R.drawable.e7_item_icon_eq_boot_dem007
    "ecd6h",
    "ecd6h_chaos",
    "ecd6h_craft",
    "ecd6h_craft_chaos",
    -> R.drawable.e7_item_icon_eq_helm_dem006
    "ecd6h_chaos_u",
    "ecd6h_craft_chaos_u",
    "ecd6h_craft_u",
    "ecd6h_u",
    -> R.drawable.e7_item_icon_eq_helm_dem007
    "ecd6n",
    "ecd6n_chaos",
    "ecd6n_craft",
    "ecd6n_craft_chaos",
    -> R.drawable.e7_item_icon_eq_neck_dem006
    "ecd6n_chaos_u",
    "ecd6n_craft_chaos_u",
    "ecd6n_craft_u",
    "ecd6n_u",
    -> R.drawable.e7_item_icon_eq_neck_dem007
    "ecd6r",
    "ecd6r_chaos",
    "ecd6r_craft",
    "ecd6r_craft_chaos",
    -> R.drawable.e7_item_icon_eq_ring_dem006
    "ecd6r_chaos_u",
    "ecd6r_craft_chaos_u",
    "ecd6r_craft_u",
    "ecd6r_u",
    -> R.drawable.e7_item_icon_eq_ring_dem007
    "ecd6w",
    "ecd6w_chaos",
    "ecd6w_craft",
    "ecd6w_craft_chaos",
    -> R.drawable.e7_item_icon_eq_weapon_dem006
    "ecd6w_chaos_u",
    "ecd6w_craft_chaos_u",
    "ecd6w_craft_u",
    "ecd6w_u",
    -> R.drawable.e7_item_icon_eq_weapon_dem007
    else -> null
}

@DrawableRes
private fun gearItemIcon_ecep(code: String): Int? = when (code) {
    "ecep_a",
    -> R.drawable.e7_item_icon_eq_armor_jpncele001
    "ecep_b",
    -> R.drawable.e7_item_icon_eq_boot_jpncele001
    "ecep_h",
    -> R.drawable.e7_item_icon_eq_helm_jpncele001
    "ecep_n",
    -> R.drawable.e7_item_icon_eq_neck_orb005
    "ecep_r",
    -> R.drawable.e7_item_icon_eq_ring_cidonia003
    "ecep_w",
    -> R.drawable.e7_item_icon_eq_weapon_jpncele001
    else -> null
}

@DrawableRes
private fun gearItemIcon_ecg6(code: String): Int? = when (code) {
    "ecg6a",
    "ecg6a_chaos",
    "ecg6a_craft",
    "ecg6a_craft_chaos",
    -> R.drawable.e7_item_icon_eq_armor_ore006
    "ecg6a_chaos_u",
    "ecg6a_craft_chaos_u",
    "ecg6a_craft_u",
    "ecg6a_u",
    -> R.drawable.e7_item_icon_eq_armor_ore007
    "ecg6b",
    "ecg6b_chaos",
    "ecg6b_craft",
    "ecg6b_craft_chaos",
    -> R.drawable.e7_item_icon_eq_boot_ore006
    "ecg6b_chaos_u",
    "ecg6b_craft_chaos_u",
    "ecg6b_craft_u",
    "ecg6b_u",
    -> R.drawable.e7_item_icon_eq_boot_ore007
    "ecg6h",
    "ecg6h_chaos",
    "ecg6h_craft",
    "ecg6h_craft_chaos",
    -> R.drawable.e7_item_icon_eq_helm_ore006
    "ecg6h_chaos_u",
    "ecg6h_craft_chaos_u",
    "ecg6h_craft_u",
    "ecg6h_u",
    -> R.drawable.e7_item_icon_eq_helm_ore007
    "ecg6n",
    "ecg6n_chaos",
    "ecg6n_craft",
    "ecg6n_craft_chaos",
    -> R.drawable.e7_item_icon_eq_neck_ore006
    "ecg6n_chaos_u",
    "ecg6n_craft_chaos_u",
    "ecg6n_craft_u",
    "ecg6n_u",
    -> R.drawable.e7_item_icon_eq_neck_ore007
    "ecg6r",
    "ecg6r_chaos",
    "ecg6r_craft",
    "ecg6r_craft_chaos",
    -> R.drawable.e7_item_icon_eq_ring_ore106
    "ecg6r_chaos_u",
    "ecg6r_craft_chaos_u",
    "ecg6r_craft_u",
    "ecg6r_u",
    -> R.drawable.e7_item_icon_eq_ring_ore107
    "ecg6w",
    "ecg6w_chaos",
    "ecg6w_craft",
    "ecg6w_craft_chaos",
    -> R.drawable.e7_item_icon_eq_weapon_ore006
    "ecg6w_chaos_u",
    "ecg6w_craft_chaos_u",
    "ecg6w_craft_u",
    "ecg6w_u",
    -> R.drawable.e7_item_icon_eq_weapon_ore007
    else -> null
}

@DrawableRes
private fun gearItemIcon_ecl2(code: String): Int? = when (code) {
    "ecl23r",
    -> R.drawable.e7_item_icon_eq_ring_ecl2023
    "ecl24r",
    -> R.drawable.e7_item_icon_eq_ring_ecl2024
    "ecl25r",
    -> R.drawable.e7_item_icon_eq_ring_ecl2025
    else -> null
}

@DrawableRes
private fun gearItemIcon_ecn2(code: String): Int? = when (code) {
    "ecn23r",
    -> R.drawable.e7_item_icon_eq_ring_ecn2023
    else -> null
}

@DrawableRes
private fun gearItemIcon_econ(code: String): Int? = when (code) {
    "econd1a",
    "econf1a",
    "econi1a",
    "econl1a",
    "econw1a",
    -> R.drawable.e7_item_icon_eq_armor_legendanc002
    "econd1b",
    "econf1b",
    "econi1b",
    "econl1b",
    "econw1b",
    -> R.drawable.e7_item_icon_eq_boot_legendanc002
    "econd1h",
    "econf1h",
    "econi1h",
    "econl1h",
    "econw1h",
    -> R.drawable.e7_item_icon_eq_helm_legendanc002
    "econd1n",
    "econf1n",
    "econi1n",
    "econl1n",
    "econw1n",
    -> R.drawable.e7_item_icon_eq_neck_legendanc002
    "econd1r",
    "econf1r",
    "econi1r",
    "econl1r",
    "econw1r",
    -> R.drawable.e7_item_icon_eq_ring_legendanc002
    "econd1w",
    "econf1w",
    "econi1w",
    "econl1w",
    "econw1w",
    -> R.drawable.e7_item_icon_eq_weapon_legendanc002
    else -> null
}

@DrawableRes
private fun gearItemIcon_ecp6(code: String): Int? = when (code) {
    "ecp6a",
    "ecp6a_chaos",
    "ecp6a_craft",
    "ecp6a_craft_chaos",
    -> R.drawable.e7_item_icon_eq_armor_pas006
    "ecp6a_chaos_u",
    "ecp6a_craft_chaos_u",
    "ecp6a_craft_u",
    "ecp6a_u",
    -> R.drawable.e7_item_icon_eq_armor_pas006_u
    "ecp6b",
    "ecp6b_chaos",
    "ecp6b_craft",
    "ecp6b_craft_chaos",
    -> R.drawable.e7_item_icon_eq_boot_pas006
    "ecp6b_chaos_u",
    "ecp6b_craft_chaos_u",
    "ecp6b_craft_u",
    "ecp6b_u",
    -> R.drawable.e7_item_icon_eq_boot_pas006_u
    "ecp6h",
    "ecp6h_chaos",
    "ecp6h_craft",
    "ecp6h_craft_chaos",
    -> R.drawable.e7_item_icon_eq_helm_pas006
    "ecp6h_chaos_u",
    "ecp6h_craft_chaos_u",
    "ecp6h_craft_u",
    "ecp6h_u",
    -> R.drawable.e7_item_icon_eq_helm_pas006_u
    "ecp6n",
    "ecp6n_chaos",
    "ecp6n_craft",
    "ecp6n_craft_chaos",
    -> R.drawable.e7_item_icon_eq_neck_pas006
    "ecp6n_chaos_u",
    "ecp6n_craft_chaos_u",
    "ecp6n_craft_u",
    "ecp6n_u",
    -> R.drawable.e7_item_icon_eq_neck_pas006_u
    "ecp6r",
    "ecp6r_chaos",
    "ecp6r_craft",
    "ecp6r_craft_chaos",
    -> R.drawable.e7_item_icon_eq_ring_pas006
    "ecp6r_chaos_u",
    "ecp6r_craft_chaos_u",
    "ecp6r_craft_u",
    "ecp6r_u",
    -> R.drawable.e7_item_icon_eq_ring_pas006_u
    "ecp6w",
    "ecp6w_chaos",
    "ecp6w_craft",
    "ecp6w_craft_chaos",
    -> R.drawable.e7_item_icon_eq_weapon_pas006
    "ecp6w_chaos_u",
    "ecp6w_craft_chaos_u",
    "ecp6w_craft_u",
    "ecp6w_u",
    -> R.drawable.e7_item_icon_eq_weapon_pas006_u
    else -> null
}

@DrawableRes
private fun gearItemIcon_ecp7(code: String): Int? = when (code) {
    "ecp7a",
    -> R.drawable.e7_item_icon_eq_armor_pas007
    "ecp7b",
    -> R.drawable.e7_item_icon_eq_boot_pas007
    "ecp7h",
    -> R.drawable.e7_item_icon_eq_helm_pas007
    "ecp7n",
    -> R.drawable.e7_item_icon_eq_neck_pas007
    "ecp7r",
    -> R.drawable.e7_item_icon_eq_ring_pas007
    "ecp7w",
    -> R.drawable.e7_item_icon_eq_weapon_pas007
    else -> null
}

@DrawableRes
private fun gearItemIcon_ecq6(code: String): Int? = when (code) {
    "ecq6a",
    "ecq6a_chaos",
    "ecq6a_craft",
    "ecq6a_craft_chaos",
    -> R.drawable.e7_item_icon_eq_armor_que006
    "ecq6a_chaos_u",
    "ecq6a_craft_chaos_u",
    "ecq6a_craft_u",
    "ecq6a_u",
    -> R.drawable.e7_item_icon_eq_armor_que007
    "ecq6b",
    "ecq6b_chaos",
    "ecq6b_craft",
    "ecq6b_craft_chaos",
    -> R.drawable.e7_item_icon_eq_boot_que006
    "ecq6b_chaos_u",
    "ecq6b_craft_chaos_u",
    "ecq6b_craft_u",
    "ecq6b_u",
    -> R.drawable.e7_item_icon_eq_boot_que007
    "ecq6h",
    "ecq6h_chaos",
    "ecq6h_craft",
    "ecq6h_craft_chaos",
    -> R.drawable.e7_item_icon_eq_helm_que006
    "ecq6h_chaos_u",
    "ecq6h_craft_chaos_u",
    "ecq6h_craft_u",
    "ecq6h_u",
    -> R.drawable.e7_item_icon_eq_helm_que007
    "ecq6n",
    "ecq6n_chaos",
    "ecq6n_craft",
    "ecq6n_craft_chaos",
    -> R.drawable.e7_item_icon_eq_neck_que006
    "ecq6n_chaos_u",
    "ecq6n_craft_chaos_u",
    "ecq6n_craft_u",
    "ecq6n_u",
    -> R.drawable.e7_item_icon_eq_neck_que007
    "ecq6r",
    "ecq6r_chaos",
    "ecq6r_craft",
    "ecq6r_craft_chaos",
    -> R.drawable.e7_item_icon_eq_ring_que006
    "ecq6r_chaos_u",
    "ecq6r_craft_chaos_u",
    "ecq6r_craft_u",
    "ecq6r_u",
    -> R.drawable.e7_item_icon_eq_ring_que007
    "ecq6w",
    "ecq6w_chaos",
    "ecq6w_craft",
    "ecq6w_craft_chaos",
    -> R.drawable.e7_item_icon_eq_weapon_que006
    "ecq6w_chaos_u",
    "ecq6w_craft_chaos_u",
    "ecq6w_craft_u",
    "ecq6w_u",
    -> R.drawable.e7_item_icon_eq_weapon_que007
    else -> null
}

@DrawableRes
private fun gearItemIcon_ecs1(code: String): Int? = when (code) {
    "ecs19a",
    -> R.drawable.e7_item_icon_eq_armor_cstory019
    "ecs16h",
    -> R.drawable.e7_item_icon_eq_helm_cstory016
    "ecs17h",
    -> R.drawable.e7_item_icon_eq_helm_cstory017
    "ecs14n",
    -> R.drawable.e7_item_icon_eq_neck_cstory014
    "ecs16n",
    -> R.drawable.e7_item_icon_eq_neck_cstory016
    "ecs18n",
    -> R.drawable.e7_item_icon_eq_neck_cstory018
    "ecs15w",
    -> R.drawable.e7_item_icon_eq_weapon_cstory015
    "ecs16w",
    -> R.drawable.e7_item_icon_eq_weapon_cstory016
    else -> null
}

@DrawableRes
private fun gearItemIcon_ecs2(code: String): Int? = when (code) {
    "ecs25a",
    -> R.drawable.e7_item_icon_eq_armor_c5147
    "ecs20a",
    -> R.drawable.e7_item_icon_eq_armor_cstory020
    "ecs21a",
    -> R.drawable.e7_item_icon_eq_armor_cstory021
    "ecs25b",
    -> R.drawable.e7_item_icon_eq_boot_c5190
    "ecs20b",
    -> R.drawable.e7_item_icon_eq_boot_cstory020
    "ecs22b",
    -> R.drawable.e7_item_icon_eq_boot_cstory022
    "ecs24b",
    -> R.drawable.e7_item_icon_eq_boot_cstory024
    "ecs25h",
    -> R.drawable.e7_item_icon_eq_helm_c2148
    "ecs20h",
    -> R.drawable.e7_item_icon_eq_helm_cstory020
    "ecs21h",
    -> R.drawable.e7_item_icon_eq_helm_cstory021
    "ecs22h",
    -> R.drawable.e7_item_icon_eq_helm_cstory022
    "ecs23h",
    -> R.drawable.e7_item_icon_eq_helm_cstory023
    "ecs25n",
    -> R.drawable.e7_item_icon_eq_neck_c2148
    "ecs20n",
    -> R.drawable.e7_item_icon_eq_neck_cstory020
    "ecs25r",
    -> R.drawable.e7_item_icon_eq_ring_c5147
    "ecs20r",
    -> R.drawable.e7_item_icon_eq_ring_cstory020
    "ecs21r",
    -> R.drawable.e7_item_icon_eq_ring_cstory021
    "ecs23r",
    -> R.drawable.e7_item_icon_eq_ring_cstory023
    "ecs24r",
    -> R.drawable.e7_item_icon_eq_ring_cstory024
    "ecs25w",
    -> R.drawable.e7_item_icon_eq_weapon_c5190
    "ecs20w",
    -> R.drawable.e7_item_icon_eq_weapon_cstory020
    "ecs21w",
    -> R.drawable.e7_item_icon_eq_weapon_cstory021
    "ecs22w",
    -> R.drawable.e7_item_icon_eq_weapon_cstory022
    else -> null
}

@DrawableRes
private fun gearItemIcon_ecw6(code: String): Int? = when (code) {
    "ecw6a",
    "ecw6a_chaos",
    "ecw6a_craft",
    "ecw6a_craft_chaos",
    -> R.drawable.e7_item_icon_eq_armor_bone006
    "ecw6a_chaos_u",
    "ecw6a_craft_chaos_u",
    "ecw6a_craft_u",
    "ecw6a_u",
    -> R.drawable.e7_item_icon_eq_armor_bone007
    "ecw6b",
    "ecw6b_chaos",
    "ecw6b_craft",
    "ecw6b_craft_chaos",
    -> R.drawable.e7_item_icon_eq_boot_bone006
    "ecw6b_chaos_u",
    "ecw6b_craft_chaos_u",
    "ecw6b_craft_u",
    "ecw6b_u",
    -> R.drawable.e7_item_icon_eq_boot_bone007
    "ecw6h",
    "ecw6h_chaos",
    "ecw6h_craft",
    "ecw6h_craft_chaos",
    -> R.drawable.e7_item_icon_eq_helm_bone006
    "ecw6h_chaos_u",
    "ecw6h_craft_chaos_u",
    "ecw6h_craft_u",
    "ecw6h_u",
    -> R.drawable.e7_item_icon_eq_helm_bone007
    "ecw6n",
    "ecw6n_chaos",
    "ecw6n_craft",
    "ecw6n_craft_chaos",
    -> R.drawable.e7_item_icon_eq_neck_bone006
    "ecw6n_chaos_u",
    "ecw6n_craft_chaos_u",
    "ecw6n_craft_u",
    "ecw6n_u",
    -> R.drawable.e7_item_icon_eq_neck_bone007
    "ecw6r",
    "ecw6r_chaos",
    "ecw6r_craft",
    "ecw6r_craft_chaos",
    -> R.drawable.e7_item_icon_eq_ring_bone106
    "ecw6r_chaos_u",
    "ecw6r_craft_chaos_u",
    "ecw6r_craft_u",
    "ecw6r_u",
    -> R.drawable.e7_item_icon_eq_ring_bone107
    "ecw6w",
    "ecw6w_chaos",
    "ecw6w_craft",
    "ecw6w_craft_chaos",
    -> R.drawable.e7_item_icon_eq_weapon_bone006
    "ecw6w_chaos_u",
    "ecw6w_craft_chaos_u",
    "ecw6w_craft_u",
    "ecw6w_u",
    -> R.drawable.e7_item_icon_eq_weapon_bone007
    else -> null
}

@DrawableRes
private fun gearItemIcon_edb6(code: String): Int? = when (code) {
    "edb6a",
    -> R.drawable.e7_item_icon_eq_armor_orb006
    "edb6a_u",
    -> R.drawable.e7_item_icon_eq_armor_orb007
    "edb6b",
    -> R.drawable.e7_item_icon_eq_boot_orb006
    "edb6b_u",
    -> R.drawable.e7_item_icon_eq_boot_orb007
    "edb6h",
    -> R.drawable.e7_item_icon_eq_helm_orb006
    "edb6h_u",
    -> R.drawable.e7_item_icon_eq_helm_orb007
    "edb6n",
    -> R.drawable.e7_item_icon_eq_neck_orb006
    "edb6n_u",
    -> R.drawable.e7_item_icon_eq_neck_orb007
    "edb6r",
    -> R.drawable.e7_item_icon_eq_ring_orb106
    "edb6r_u",
    -> R.drawable.e7_item_icon_eq_ring_orb107
    "edb6w",
    -> R.drawable.e7_item_icon_eq_weapon_orb006
    "edb6w_u",
    -> R.drawable.e7_item_icon_eq_weapon_orb007
    else -> null
}

@DrawableRes
private fun gearItemIcon_edd6(code: String): Int? = when (code) {
    "edd6a",
    -> R.drawable.e7_item_icon_eq_armor_dem006
    "edd6a_u",
    -> R.drawable.e7_item_icon_eq_armor_dem007
    "edd6b",
    -> R.drawable.e7_item_icon_eq_boot_dem006
    "edd6b_u",
    -> R.drawable.e7_item_icon_eq_boot_dem007
    "edd6h",
    -> R.drawable.e7_item_icon_eq_helm_dem006
    "edd6h_u",
    -> R.drawable.e7_item_icon_eq_helm_dem007
    "edd6n",
    -> R.drawable.e7_item_icon_eq_neck_dem006
    "edd6n_u",
    -> R.drawable.e7_item_icon_eq_neck_dem007
    "edd6r",
    -> R.drawable.e7_item_icon_eq_ring_dem006
    "edd6r_u",
    -> R.drawable.e7_item_icon_eq_ring_dem007
    "edd6w",
    -> R.drawable.e7_item_icon_eq_weapon_dem006
    "edd6w_u",
    -> R.drawable.e7_item_icon_eq_weapon_dem007
    else -> null
}

@DrawableRes
private fun gearItemIcon_edg6(code: String): Int? = when (code) {
    "edg6a",
    -> R.drawable.e7_item_icon_eq_armor_ore006
    "edg6a_u",
    -> R.drawable.e7_item_icon_eq_armor_ore007
    "edg6b",
    -> R.drawable.e7_item_icon_eq_boot_ore006
    "edg6b_u",
    -> R.drawable.e7_item_icon_eq_boot_ore007
    "edg6h",
    -> R.drawable.e7_item_icon_eq_helm_ore006
    "edg6h_u",
    -> R.drawable.e7_item_icon_eq_helm_ore007
    "edg6n",
    -> R.drawable.e7_item_icon_eq_neck_ore006
    "edg6n_u",
    -> R.drawable.e7_item_icon_eq_neck_ore007
    "edg6r",
    -> R.drawable.e7_item_icon_eq_ring_ore106
    "edg6r_u",
    -> R.drawable.e7_item_icon_eq_ring_ore107
    "edg6w",
    -> R.drawable.e7_item_icon_eq_weapon_ore006
    "edg6w_u",
    -> R.drawable.e7_item_icon_eq_weapon_ore007
    else -> null
}

@DrawableRes
private fun gearItemIcon_edp6(code: String): Int? = when (code) {
    "edp6a",
    -> R.drawable.e7_item_icon_eq_armor_pas006
    "edp6a_u",
    -> R.drawable.e7_item_icon_eq_armor_pas006_u
    "edp6b",
    -> R.drawable.e7_item_icon_eq_boot_pas006
    "edp6b_u",
    -> R.drawable.e7_item_icon_eq_boot_pas006_u
    "edp6h",
    -> R.drawable.e7_item_icon_eq_helm_pas006
    "edp6h_u",
    -> R.drawable.e7_item_icon_eq_helm_pas006_u
    "edp6n",
    -> R.drawable.e7_item_icon_eq_neck_pas006
    "edp6n_u",
    -> R.drawable.e7_item_icon_eq_neck_pas006_u
    "edp6r",
    -> R.drawable.e7_item_icon_eq_ring_pas006
    "edp6r_u",
    -> R.drawable.e7_item_icon_eq_ring_pas006_u
    "edp6w",
    -> R.drawable.e7_item_icon_eq_weapon_pas006
    "edp6w_u",
    -> R.drawable.e7_item_icon_eq_weapon_pas006_u
    else -> null
}

@DrawableRes
private fun gearItemIcon_edq6(code: String): Int? = when (code) {
    "edq6a",
    -> R.drawable.e7_item_icon_eq_armor_que006
    "edq6a_u",
    -> R.drawable.e7_item_icon_eq_armor_que007
    "edq6b",
    -> R.drawable.e7_item_icon_eq_boot_que006
    "edq6b_u",
    -> R.drawable.e7_item_icon_eq_boot_que007
    "edq6h",
    -> R.drawable.e7_item_icon_eq_helm_que006
    "edq6h_u",
    -> R.drawable.e7_item_icon_eq_helm_que007
    "edq6n",
    -> R.drawable.e7_item_icon_eq_neck_que006
    "edq6n_u",
    -> R.drawable.e7_item_icon_eq_neck_que007
    "edq6r",
    -> R.drawable.e7_item_icon_eq_ring_que006
    "edq6r_u",
    -> R.drawable.e7_item_icon_eq_ring_que007
    "edq6w",
    -> R.drawable.e7_item_icon_eq_weapon_que006
    "edq6w_u",
    -> R.drawable.e7_item_icon_eq_weapon_que007
    else -> null
}

@DrawableRes
private fun gearItemIcon_edw6(code: String): Int? = when (code) {
    "edw6a",
    -> R.drawable.e7_item_icon_eq_armor_bone006
    "edw6a_u",
    -> R.drawable.e7_item_icon_eq_armor_bone007
    "edw6b",
    -> R.drawable.e7_item_icon_eq_boot_bone006
    "edw6b_u",
    -> R.drawable.e7_item_icon_eq_boot_bone007
    "edw6h",
    -> R.drawable.e7_item_icon_eq_helm_bone006
    "edw6h_u",
    -> R.drawable.e7_item_icon_eq_helm_bone007
    "edw6n",
    -> R.drawable.e7_item_icon_eq_neck_bone006
    "edw6n_u",
    -> R.drawable.e7_item_icon_eq_neck_bone007
    "edw6r",
    -> R.drawable.e7_item_icon_eq_ring_bone106
    "edw6r_u",
    -> R.drawable.e7_item_icon_eq_ring_bone107
    "edw6w",
    -> R.drawable.e7_item_icon_eq_weapon_bone006
    "edw6w_u",
    -> R.drawable.e7_item_icon_eq_weapon_bone007
    else -> null
}

@DrawableRes
private fun gearItemIcon_eep2(code: String): Int? = when (code) {
    "eep2_b",
    -> R.drawable.e7_item_icon_eq_boot_equippass002
    else -> null
}

@DrawableRes
private fun gearItemIcon_eep3(code: String): Int? = when (code) {
    "eep3_n",
    -> R.drawable.e7_item_icon_eq_neck_7yrpass
    else -> null
}

@DrawableRes
private fun gearItemIcon_eep_(code: String): Int? = when (code) {
    "eep_a",
    -> R.drawable.e7_item_icon_eq_armor_equippass001
    "eep_b",
    -> R.drawable.e7_item_icon_eq_boot_equippass001
    "eep_h",
    -> R.drawable.e7_item_icon_eq_helm_equippass001
    "eep_n",
    -> R.drawable.e7_item_icon_eq_neck_equippass001
    "eep_r",
    -> R.drawable.e7_item_icon_eq_ring_equippass001
    "eep_w",
    -> R.drawable.e7_item_icon_eq_weapon_equippass001
    else -> null
}

@DrawableRes
private fun gearItemIcon_eff1(code: String): Int? = when (code) {
    "eff1w",
    -> R.drawable.e7_item_icon_eq_weapon_fanfesta001
    else -> null
}

@DrawableRes
private fun gearItemIcon_egn2(code: String): Int? = when (code) {
    "egn2r",
    -> R.drawable.e7_item_icon_eq_ring_erasia001
    else -> null
}

@DrawableRes
private fun gearItemIcon_ela1(code: String): Int? = when (code) {
    "ela10a",
    "ela11a",
    "ela12a",
    "ela13a",
    "ela14a",
    "ela15a",
    "ela16a",
    "ela17a",
    -> R.drawable.e7_item_icon_eq_armor_legendanc002
    "ela10b",
    "ela11b",
    "ela12b",
    "ela13b",
    "ela14b",
    "ela15b",
    "ela16b",
    "ela17b",
    -> R.drawable.e7_item_icon_eq_boot_legendanc002
    "ela10h",
    "ela11h",
    "ela12h",
    "ela13h",
    "ela14h",
    "ela15h",
    "ela16h",
    "ela17h",
    -> R.drawable.e7_item_icon_eq_helm_legendanc002
    "ela10n",
    "ela11n",
    "ela12n",
    "ela13n",
    "ela14n",
    "ela15n",
    "ela16n",
    "ela17n",
    -> R.drawable.e7_item_icon_eq_neck_legendanc002
    "ela10r",
    "ela11r",
    "ela12r",
    "ela13r",
    "ela14r",
    "ela15r",
    "ela16r",
    "ela17r",
    -> R.drawable.e7_item_icon_eq_ring_legendanc002
    "ela10w",
    "ela11w",
    "ela12w",
    "ela13w",
    "ela14w",
    "ela15w",
    "ela16w",
    "ela17w",
    -> R.drawable.e7_item_icon_eq_weapon_legendanc002
    else -> null
}

@DrawableRes
private fun gearItemIcon_ela8(code: String): Int? = when (code) {
    "ela8a",
    -> R.drawable.e7_item_icon_eq_armor_legendanc002
    "ela8b",
    -> R.drawable.e7_item_icon_eq_boot_legendanc002
    "ela8h",
    -> R.drawable.e7_item_icon_eq_helm_legendanc002
    "ela8n",
    -> R.drawable.e7_item_icon_eq_neck_legendanc002
    "ela8r",
    -> R.drawable.e7_item_icon_eq_ring_legendanc002
    "ela8w",
    -> R.drawable.e7_item_icon_eq_weapon_legendanc002
    else -> null
}

@DrawableRes
private fun gearItemIcon_ela9(code: String): Int? = when (code) {
    "ela9a",
    -> R.drawable.e7_item_icon_eq_armor_legendanc002
    "ela9b",
    -> R.drawable.e7_item_icon_eq_boot_legendanc002
    "ela9h",
    -> R.drawable.e7_item_icon_eq_helm_legendanc002
    "ela9n",
    -> R.drawable.e7_item_icon_eq_neck_legendanc002
    "ela9r",
    -> R.drawable.e7_item_icon_eq_ring_legendanc002
    "ela9w",
    -> R.drawable.e7_item_icon_eq_weapon_legendanc002
    else -> null
}

@DrawableRes
private fun gearItemIcon_elre(code: String): Int? = when (code) {
    "elre1a",
    -> R.drawable.e7_item_icon_eq_armor_dungeon001
    "elre2a",
    -> R.drawable.e7_item_icon_eq_armor_dungeon005
    "elre3a",
    -> R.drawable.e7_item_icon_eq_armor_dungeon006
    "elre4a",
    -> R.drawable.e7_item_icon_eq_armor_dungeon008
    "elre5a",
    -> R.drawable.e7_item_icon_eq_armor_insect002
    "elre1b",
    -> R.drawable.e7_item_icon_eq_boot_dungeon001
    "elre2b",
    -> R.drawable.e7_item_icon_eq_boot_dungeon005
    "elre3b",
    -> R.drawable.e7_item_icon_eq_boot_dungeon006
    "elre4b",
    -> R.drawable.e7_item_icon_eq_boot_dungeon009
    "elre5b",
    -> R.drawable.e7_item_icon_eq_boot_insect001
    "elre1h",
    -> R.drawable.e7_item_icon_eq_helm_dungeon001
    "elre2h",
    -> R.drawable.e7_item_icon_eq_helm_dungeon005
    "elre3h",
    -> R.drawable.e7_item_icon_eq_helm_dungeon006
    "elre4h",
    -> R.drawable.e7_item_icon_eq_helm_dungeon008
    "elre5h",
    -> R.drawable.e7_item_icon_eq_helm_insect004
    "elre1n",
    -> R.drawable.e7_item_icon_eq_neck_dungeon001
    "elre2n",
    -> R.drawable.e7_item_icon_eq_neck_dungeon005
    "elre3n",
    -> R.drawable.e7_item_icon_eq_neck_dungeon006
    "elre4n",
    -> R.drawable.e7_item_icon_eq_neck_dungeon009
    "elre1r",
    -> R.drawable.e7_item_icon_eq_ring_dungeon001
    "elre2r",
    -> R.drawable.e7_item_icon_eq_ring_dungeon005
    "elre3r",
    -> R.drawable.e7_item_icon_eq_ring_dungeon006
    "elre4r",
    -> R.drawable.e7_item_icon_eq_ring_dungeon009
    "elre5r",
    -> R.drawable.e7_item_icon_eq_ring_insect005
    "elre1w",
    -> R.drawable.e7_item_icon_eq_weapon_dungeon001
    "elre2w",
    -> R.drawable.e7_item_icon_eq_weapon_dungeon005
    "elre3w",
    -> R.drawable.e7_item_icon_eq_weapon_dungeon006
    "elre4w",
    -> R.drawable.e7_item_icon_eq_weapon_dungeon008
    "elre5w",
    -> R.drawable.e7_item_icon_eq_weapon_insect003
    else -> null
}

@DrawableRes
private fun gearItemIcon_emp1(code: String): Int? = when (code) {
    "emp12_a",
    -> R.drawable.e7_item_icon_eq_armor_c2185_1
    "emp13_a",
    -> R.drawable.e7_item_icon_eq_armor_c2185_2
    "emp1_r",
    -> R.drawable.e7_item_icon_eq_armor_mlpack001
    "emp14_b",
    -> R.drawable.e7_item_icon_eq_boot_c2148
    "emp10_b",
    -> R.drawable.e7_item_icon_eq_boot_c2181
    "emp12_b",
    -> R.drawable.e7_item_icon_eq_boot_c2185_1
    "emp13_b",
    -> R.drawable.e7_item_icon_eq_boot_c2185_2
    "emp1_b",
    -> R.drawable.e7_item_icon_eq_boot_mlpack001
    "emp10_h",
    -> R.drawable.e7_item_icon_eq_helm_c2181
    "emp12_h",
    -> R.drawable.e7_item_icon_eq_helm_c2185_1
    "emp13_h",
    -> R.drawable.e7_item_icon_eq_helm_c2185_2
    "emp1_h",
    -> R.drawable.e7_item_icon_eq_helm_mlpack001
    "emp10_n",
    -> R.drawable.e7_item_icon_eq_neck_c2181
    "emp12_n",
    -> R.drawable.e7_item_icon_eq_neck_c2185_1
    "emp13_n",
    -> R.drawable.e7_item_icon_eq_neck_c2185_2
    "emp1_n",
    -> R.drawable.e7_item_icon_eq_neck_mlpack001
    "emp10_r",
    -> R.drawable.e7_item_icon_eq_ring_c2181
    "emp12_r",
    -> R.drawable.e7_item_icon_eq_ring_c2185_1
    "emp13_r",
    -> R.drawable.e7_item_icon_eq_ring_c2185_2
    "emp1_a",
    -> R.drawable.e7_item_icon_eq_ring_mlpack001
    "emp11_w",
    -> R.drawable.e7_item_icon_eq_weapon_c2184
    "emp12_w",
    -> R.drawable.e7_item_icon_eq_weapon_c2185_1
    "emp13_w",
    -> R.drawable.e7_item_icon_eq_weapon_c2185_2
    "emp1_w",
    -> R.drawable.e7_item_icon_eq_weapon_mlpack001
    else -> null
}

@DrawableRes
private fun gearItemIcon_emp2(code: String): Int? = when (code) {
    "emp2_a",
    -> R.drawable.e7_item_icon_eq_armor_mlpack002
    "emp2_b",
    -> R.drawable.e7_item_icon_eq_boot_mlpack002
    "emp2_h",
    -> R.drawable.e7_item_icon_eq_helm_mlpack002
    "emp2_n",
    -> R.drawable.e7_item_icon_eq_neck_mlpack002
    "emp2_r",
    -> R.drawable.e7_item_icon_eq_ring_mlpack002
    "emp2_w",
    -> R.drawable.e7_item_icon_eq_weapon_mlpack002
    else -> null
}

@DrawableRes
private fun gearItemIcon_emp3(code: String): Int? = when (code) {
    "emp3_w",
    -> R.drawable.e7_item_icon_eq_weapon_mmk
    else -> null
}

@DrawableRes
private fun gearItemIcon_emp4(code: String): Int? = when (code) {
    "emp4_a",
    -> R.drawable.e7_item_icon_eq_armor_prequel
    "emp4_b",
    -> R.drawable.e7_item_icon_eq_boot_prequel
    "emp4_h",
    -> R.drawable.e7_item_icon_eq_helm_prequel
    "emp4_n",
    -> R.drawable.e7_item_icon_eq_neck_prequel
    "emp4_r",
    -> R.drawable.e7_item_icon_eq_ring_prequel
    "emp4_w",
    -> R.drawable.e7_item_icon_eq_weapon_prequel
    else -> null
}

@DrawableRes
private fun gearItemIcon_emp5(code: String): Int? = when (code) {
    "emp5_a",
    -> R.drawable.e7_item_icon_eq_armor_linak
    "emp5_b",
    -> R.drawable.e7_item_icon_eq_boot_linak
    "emp5_h",
    -> R.drawable.e7_item_icon_eq_helm_linak
    "emp5_n",
    -> R.drawable.e7_item_icon_eq_neck_linak
    "emp5_r",
    -> R.drawable.e7_item_icon_eq_ring_linak
    "emp5_w",
    -> R.drawable.e7_item_icon_eq_weapon_linak
    else -> null
}

@DrawableRes
private fun gearItemIcon_emp6(code: String): Int? = when (code) {
    "emp6_a",
    -> R.drawable.e7_item_icon_eq_armor_tenebria_01
    "emp6_b",
    -> R.drawable.e7_item_icon_eq_boot_tenebria_01
    "emp6_h",
    -> R.drawable.e7_item_icon_eq_helm_tenebria_01
    "emp6_n",
    -> R.drawable.e7_item_icon_eq_neck_tenebria_01
    "emp6_r",
    -> R.drawable.e7_item_icon_eq_ring_tenebria_01
    "emp6_w",
    -> R.drawable.e7_item_icon_eq_weapon_tenebria_01
    else -> null
}

@DrawableRes
private fun gearItemIcon_emp7(code: String): Int? = when (code) {
    "emp7_a",
    -> R.drawable.e7_item_icon_eq_armor_fullpack_01
    "emp7_b",
    -> R.drawable.e7_item_icon_eq_boot_fullpack_01
    "emp7_h",
    -> R.drawable.e7_item_icon_eq_helm_fullpack_01
    "emp7_n",
    -> R.drawable.e7_item_icon_eq_neck_fullpack_01
    "emp7_r",
    -> R.drawable.e7_item_icon_eq_ring_fullpack_01
    "emp7_w",
    -> R.drawable.e7_item_icon_eq_weapon_fullpack_01
    else -> null
}

@DrawableRes
private fun gearItemIcon_emp8(code: String): Int? = when (code) {
    "emp8_a",
    -> R.drawable.e7_item_icon_eq_armor_fullpack_02
    "emp8_b",
    -> R.drawable.e7_item_icon_eq_boot_fullpack_02
    "emp8_h",
    -> R.drawable.e7_item_icon_eq_helm_fullpack_02
    "emp8_n",
    -> R.drawable.e7_item_icon_eq_neck_fullpack_02
    "emp8_r",
    -> R.drawable.e7_item_icon_eq_ring_fullpack_02
    "emp8_w",
    -> R.drawable.e7_item_icon_eq_weapon_fullpack_02
    else -> null
}

@DrawableRes
private fun gearItemIcon_emp9(code: String): Int? = when (code) {
    "emp9_h",
    -> R.drawable.e7_item_icon_eq_helm_iseria001
    else -> null
}

@DrawableRes
private fun gearItemIcon_ems2(code: String): Int? = when (code) {
    "ems26n",
    -> R.drawable.e7_item_icon_eq_neck_e7masters26
    else -> null
}

@DrawableRes
private fun gearItemIcon_eorb(code: String): Int? = when (code) {
    "eorbis1a",
    -> R.drawable.e7_item_icon_eq_armor_orbisheart
    "eorbis1b",
    -> R.drawable.e7_item_icon_eq_boot_orbisheart
    "eorbis1h",
    -> R.drawable.e7_item_icon_eq_helm_orbisheart
    "eorbis1n",
    -> R.drawable.e7_item_icon_eq_neck_orbisheart
    "eorbis1r",
    -> R.drawable.e7_item_icon_eq_ring_orbisheart
    "eorbis1w",
    -> R.drawable.e7_item_icon_eq_weapon_orbisheart
    else -> null
}

@DrawableRes
private fun gearItemIcon_erp1(code: String): Int? = when (code) {
    "erp1_a",
    -> R.drawable.e7_item_icon_eq_armor_attpack002
    "erp1_b",
    -> R.drawable.e7_item_icon_eq_boot_attpack002
    "erp1_h",
    -> R.drawable.e7_item_icon_eq_helm_attpack002
    "erp1_n",
    -> R.drawable.e7_item_icon_eq_neck_attpack002
    "erp1_r",
    -> R.drawable.e7_item_icon_eq_ring_attpack002
    "erp1_w",
    -> R.drawable.e7_item_icon_eq_weapon_attpack002
    else -> null
}

@DrawableRes
private fun gearItemIcon_erp2(code: String): Int? = when (code) {
    "erp2_a",
    -> R.drawable.e7_item_icon_eq_armor_erpack002
    "erp2_b",
    -> R.drawable.e7_item_icon_eq_boot_erpack002
    "erp2_h",
    -> R.drawable.e7_item_icon_eq_helm_erpack002
    "erp2_n",
    -> R.drawable.e7_item_icon_eq_neck_erpack002
    "erp2_r",
    -> R.drawable.e7_item_icon_eq_ring_erpack002
    "erp2_w",
    -> R.drawable.e7_item_icon_eq_weapon_erpack002
    else -> null
}

@DrawableRes
private fun gearItemIcon_erp3(code: String): Int? = when (code) {
    "erp3_a",
    -> R.drawable.e7_item_icon_eq_armor_erpack003
    "erp3_b",
    -> R.drawable.e7_item_icon_eq_boot_erpack003
    "erp3_h",
    -> R.drawable.e7_item_icon_eq_helm_erpack003
    "erp3_n",
    -> R.drawable.e7_item_icon_eq_neck_erpack003
    "erp3_r",
    -> R.drawable.e7_item_icon_eq_ring_erpack003
    "erp3_w",
    -> R.drawable.e7_item_icon_eq_weapon_erpack003
    else -> null
}

@DrawableRes
private fun gearItemIcon_erp4(code: String): Int? = when (code) {
    "erp4_a",
    -> R.drawable.e7_item_icon_eq_armor_c6005
    "erp4_b",
    -> R.drawable.e7_item_icon_eq_boot_c6005
    "erp4_h",
    -> R.drawable.e7_item_icon_eq_helm_c6005
    "erp4_n",
    -> R.drawable.e7_item_icon_eq_neck_c6005
    "erp4_r",
    -> R.drawable.e7_item_icon_eq_ring_c6005
    "erp4_w",
    -> R.drawable.e7_item_icon_eq_weapon_c6005
    else -> null
}

@DrawableRes
private fun gearItemIcon_esc0(code: String): Int? = when (code) {
    "esc01a",
    -> R.drawable.e7_item_icon_eq_armor_gob001
    "esc01b",
    -> R.drawable.e7_item_icon_eq_boot_gob001
    "esc01h",
    -> R.drawable.e7_item_icon_eq_helm_gob001
    "esc01n",
    -> R.drawable.e7_item_icon_eq_neck_gob001
    "esc01r",
    -> R.drawable.e7_item_icon_eq_ring_gob001
    "esc01w",
    -> R.drawable.e7_item_icon_eq_weapon_gob001
    else -> null
}

@DrawableRes
private fun gearItemIcon_ese1(code: String): Int? = when (code) {
    "ese1n",
    -> R.drawable.e7_item_icon_eq_neck_sevent001
    else -> null
}

@DrawableRes
private fun gearItemIcon_esh1(code: String): Int? = when (code) {
    "esh1_a",
    -> R.drawable.e7_item_icon_eq_armor_gob001
    "esh1_b",
    -> R.drawable.e7_item_icon_eq_boot_gob001
    "esh1_h",
    -> R.drawable.e7_item_icon_eq_helm_gob001
    "esh1_n",
    -> R.drawable.e7_item_icon_eq_neck_gob001
    "esh1_r",
    -> R.drawable.e7_item_icon_eq_ring_gob001
    "esh1_w",
    -> R.drawable.e7_item_icon_eq_weapon_gob001
    else -> null
}

@DrawableRes
private fun gearItemIcon_esh2(code: String): Int? = when (code) {
    "esh2_a",
    -> R.drawable.e7_item_icon_eq_armor_dash001
    "esh2_b",
    -> R.drawable.e7_item_icon_eq_boot_dash001
    "esh2_h",
    -> R.drawable.e7_item_icon_eq_helm_dash001
    "esh2_n",
    -> R.drawable.e7_item_icon_eq_neck_dash001
    "esh2_r",
    -> R.drawable.e7_item_icon_eq_ring_dash001
    "esh2_w",
    -> R.drawable.e7_item_icon_eq_weapon_dash001
    else -> null
}

@DrawableRes
private fun gearItemIcon_esh3(code: String): Int? = when (code) {
    "esh3_a",
    -> R.drawable.e7_item_icon_eq_armor_dash002
    "esh3_b",
    -> R.drawable.e7_item_icon_eq_boot_dash002
    "esh3_h",
    -> R.drawable.e7_item_icon_eq_helm_dash002
    "esh3_n",
    -> R.drawable.e7_item_icon_eq_neck_dash002
    "esh3_r",
    -> R.drawable.e7_item_icon_eq_ring_dash002
    "esh3_w",
    -> R.drawable.e7_item_icon_eq_weapon_dash002
    else -> null
}

@DrawableRes
private fun gearItemIcon_espb(code: String): Int? = when (code) {
    "espb6a",
    "espb_cd6a",
    "espb_ct6a",
    "espb_ct6a2",
    "espb_res6a",
    -> R.drawable.e7_item_icon_eq_armor_orb006
    "espb6a_u",
    "espb_cd6a_u",
    "espb_ct6a2_u",
    "espb_ct6a_u",
    "espb_res6a_u",
    -> R.drawable.e7_item_icon_eq_armor_orb007
    "espb6b",
    "espb_cd6b",
    "espb_cd6b2",
    "espb_cd6b3",
    "espb_ct6b",
    "espb_ct6b2",
    "espb_ct6b3",
    "espb_res6b",
    -> R.drawable.e7_item_icon_eq_boot_orb006
    "espb6b_u",
    "espb_cd6b2_u",
    "espb_cd6b3_u",
    "espb_cd6b_u",
    "espb_ct6b2_u",
    "espb_ct6b3_u",
    "espb_ct6b_u",
    "espb_res6b_u",
    -> R.drawable.e7_item_icon_eq_boot_orb007
    "espb6h",
    "espb_cd6h",
    "espb_cd6h2",
    "espb_ct6h",
    "espb_ct6h2",
    "espb_res6h",
    -> R.drawable.e7_item_icon_eq_helm_orb006
    "espb6h_u",
    "espb_cd6h2_u",
    "espb_cd6h_u",
    "espb_ct6h2_u",
    "espb_ct6h_u",
    "espb_res6h_u",
    -> R.drawable.e7_item_icon_eq_helm_orb007
    "espb6n",
    "espb_cd6n",
    "espb_cd6n2",
    "espb_ct6n",
    "espb_ct6n2",
    "espb_res6n",
    -> R.drawable.e7_item_icon_eq_neck_orb006
    "espb6n_u",
    "espb_cd6n2_u",
    "espb_cd6n_u",
    "espb_ct6n2_u",
    "espb_ct6n_u",
    "espb_res6n_u",
    -> R.drawable.e7_item_icon_eq_neck_orb007
    "espb6r",
    "espb_cd6r",
    "espb_cd6r2",
    "espb_ct6r",
    "espb_ct6r2",
    "espb_res6r",
    -> R.drawable.e7_item_icon_eq_ring_orb106
    "espb6r_u",
    "espb_cd6r2_u",
    "espb_cd6r_u",
    "espb_ct6r2_u",
    "espb_ct6r_u",
    "espb_res6r_u",
    -> R.drawable.e7_item_icon_eq_ring_orb107
    "espb6w",
    "espb_cd6w",
    "espb_cd6w2",
    "espb_ct6w",
    "espb_ct6w2",
    "espb_res6w",
    -> R.drawable.e7_item_icon_eq_weapon_orb006
    "espb6w_u",
    "espb_cd6w2_u",
    "espb_cd6w_u",
    "espb_ct6w2_u",
    "espb_ct6w_u",
    "espb_res6w_u",
    -> R.drawable.e7_item_icon_eq_weapon_orb007
    else -> null
}

@DrawableRes
private fun gearItemIcon_espd(code: String): Int? = when (code) {
    "espd6a",
    "espd_pe6a",
    "espd_to6a",
    -> R.drawable.e7_item_icon_eq_armor_dem006
    "espd6a_u",
    "espd_pe6a_u",
    "espd_to6a_u",
    -> R.drawable.e7_item_icon_eq_armor_dem007
    "espd6b",
    "espd_pe6b",
    "espd_to6b",
    -> R.drawable.e7_item_icon_eq_boot_dem006
    "espd6b_u",
    "espd_pe6b_u",
    "espd_to6b_u",
    -> R.drawable.e7_item_icon_eq_boot_dem007
    "espd6h",
    "espd_pe6h",
    "espd_to6h",
    -> R.drawable.e7_item_icon_eq_helm_dem006
    "espd6h_u",
    "espd_pe6h_u",
    "espd_to6h_u",
    -> R.drawable.e7_item_icon_eq_helm_dem007
    "espd6n",
    "espd_pe6n",
    "espd_to6n",
    -> R.drawable.e7_item_icon_eq_neck_dem006
    "espd6n_u",
    "espd_pe6n_u",
    "espd_to6n_u",
    -> R.drawable.e7_item_icon_eq_neck_dem007
    "espd6r",
    "espd_pe6r",
    "espd_to6r",
    -> R.drawable.e7_item_icon_eq_ring_dem006
    "espd6r_u",
    "espd_pe6r_u",
    "espd_to6r_u",
    -> R.drawable.e7_item_icon_eq_ring_dem007
    "espd6w",
    "espd_pe6w",
    "espd_to6w",
    -> R.drawable.e7_item_icon_eq_weapon_dem006
    "espd6w_u",
    "espd_pe6w_u",
    "espd_to6w_u",
    -> R.drawable.e7_item_icon_eq_weapon_dem007
    else -> null
}

@DrawableRes
private fun gearItemIcon_espg(code: String): Int? = when (code) {
    "espg6a",
    "espg_hp6a",
    "espg_sh6a",
    -> R.drawable.e7_item_icon_eq_armor_ore006
    "espg6a_u",
    "espg_hp6a_u",
    "espg_sh6a_u",
    -> R.drawable.e7_item_icon_eq_armor_ore007
    "espg6b",
    "espg_hp6b",
    "espg_sh6b",
    -> R.drawable.e7_item_icon_eq_boot_ore006
    "espg6b_u",
    "espg_hp6b_u",
    "espg_sh6b_u",
    -> R.drawable.e7_item_icon_eq_boot_ore007
    "espg6h",
    "espg_hp6h",
    "espg_sh6h",
    -> R.drawable.e7_item_icon_eq_helm_ore006
    "espg6h_u",
    "espg_hp6h_u",
    "espg_sh6h_u",
    -> R.drawable.e7_item_icon_eq_helm_ore007
    "espg6n",
    "espg_hp6n",
    "espg_sh6n",
    -> R.drawable.e7_item_icon_eq_neck_ore006
    "espg6n_u",
    "espg_hp6n_u",
    "espg_sh6n_u",
    -> R.drawable.e7_item_icon_eq_neck_ore007
    "espg6r",
    "espg_hp6r",
    "espg_sh6r",
    -> R.drawable.e7_item_icon_eq_ring_ore106
    "espg6r_u",
    "espg_hp6r_u",
    "espg_sh6r_u",
    -> R.drawable.e7_item_icon_eq_ring_ore107
    "espg6w",
    "espg_hp6w",
    "espg_sh6w",
    -> R.drawable.e7_item_icon_eq_weapon_ore006
    "espg6w_u",
    "espg_hp6w_u",
    "espg_sh6w_u",
    -> R.drawable.e7_item_icon_eq_weapon_ore007
    else -> null
}

@DrawableRes
private fun gearItemIcon_espp(code: String): Int? = when (code) {
    "espp6a",
    -> R.drawable.e7_item_icon_eq_armor_pas006
    "espp6a_u",
    -> R.drawable.e7_item_icon_eq_armor_pas006_u
    "espp6b",
    -> R.drawable.e7_item_icon_eq_boot_pas006
    "espp6b_u",
    -> R.drawable.e7_item_icon_eq_boot_pas006_u
    "espp6h",
    -> R.drawable.e7_item_icon_eq_helm_pas006
    "espp6h_u",
    -> R.drawable.e7_item_icon_eq_helm_pas006_u
    "espp6n",
    -> R.drawable.e7_item_icon_eq_neck_pas006
    "espp6n_u",
    -> R.drawable.e7_item_icon_eq_neck_pas006_u
    "espp6r",
    -> R.drawable.e7_item_icon_eq_ring_pas006
    "espp6r_u",
    -> R.drawable.e7_item_icon_eq_ring_pas006_u
    "espp6w",
    -> R.drawable.e7_item_icon_eq_weapon_pas006
    "espp6w_u",
    -> R.drawable.e7_item_icon_eq_weapon_pas006_u
    else -> null
}

@DrawableRes
private fun gearItemIcon_espq(code: String): Int? = when (code) {
    "espq6a",
    "espq_im6a",
    "espq_im6a2",
    "espq_im6a3",
    -> R.drawable.e7_item_icon_eq_armor_que006
    "espq6a_u",
    "espq_im6a2_u",
    "espq_im6a3_u",
    "espq_im6a_u",
    -> R.drawable.e7_item_icon_eq_armor_que007
    "espq6b",
    "espq_im6b",
    "espq_im6b2",
    -> R.drawable.e7_item_icon_eq_boot_que006
    "espq6b_u",
    "espq_im6b2_u",
    "espq_im6b_u",
    -> R.drawable.e7_item_icon_eq_boot_que007
    "espq6h",
    "espq_im6h",
    "espq_im6h2",
    "espq_im6h3",
    -> R.drawable.e7_item_icon_eq_helm_que006
    "espq6h_u",
    "espq_im6h2_u",
    "espq_im6h3_u",
    "espq_im6h_u",
    -> R.drawable.e7_item_icon_eq_helm_que007
    "espq6n",
    "espq_im6n",
    "espq_im6n2",
    -> R.drawable.e7_item_icon_eq_neck_que006
    "espq6n_u",
    "espq_im6n2_u",
    "espq_im6n_u",
    -> R.drawable.e7_item_icon_eq_neck_que007
    "espq6r",
    "espq_im6r",
    "espq_im6r2",
    -> R.drawable.e7_item_icon_eq_ring_que006
    "espq6r_u",
    "espq_im6r2_u",
    "espq_im6r_u",
    -> R.drawable.e7_item_icon_eq_ring_que007
    "espq6w",
    "espq_im6w",
    "espq_im6w2",
    -> R.drawable.e7_item_icon_eq_weapon_que006
    "espq6w_u",
    "espq_im6w2_u",
    "espq_im6w_u",
    -> R.drawable.e7_item_icon_eq_weapon_que007
    else -> null
}

@DrawableRes
private fun gearItemIcon_espw(code: String): Int? = when (code) {
    "espw6a",
    "espw_ac6a",
    "espw_cri6a",
    "espw_spd6a",
    "espw_spd6a2",
    "espw_spd6a3",
    -> R.drawable.e7_item_icon_eq_armor_bone006
    "espw6a_u",
    "espw_ac6a_u",
    "espw_cri6a_u",
    "espw_spd6a2_u",
    "espw_spd6a3_u",
    "espw_spd6a_u",
    -> R.drawable.e7_item_icon_eq_armor_bone007
    "espw6b",
    "espw6b_s",
    "espw_ac6b",
    "espw_cri6b",
    "espw_cri6b2",
    "espw_spd6b",
    "espw_spd6b2",
    -> R.drawable.e7_item_icon_eq_boot_bone006
    "espw6b_u",
    "espw_ac6b_u",
    "espw_cri6b2_u",
    "espw_cri6b_u",
    "espw_spd6b2_u",
    "espw_spd6b_u",
    -> R.drawable.e7_item_icon_eq_boot_bone007
    "espw6h",
    "espw_ac6h",
    "espw_cri6h",
    "espw_spd6h",
    "espw_spd6h2",
    "espw_spd6h3",
    -> R.drawable.e7_item_icon_eq_helm_bone006
    "espw6h_u",
    "espw_ac6h_u",
    "espw_cri6h_u",
    "espw_spd6h2_u",
    "espw_spd6h3_u",
    "espw_spd6h_u",
    -> R.drawable.e7_item_icon_eq_helm_bone007
    "espw6n",
    "espw_ac6n",
    "espw_cri6n",
    "espw_spd6n",
    "espw_spd6n2",
    "espw_spd6n3",
    -> R.drawable.e7_item_icon_eq_neck_bone006
    "espw6n_u",
    "espw_ac6n_u",
    "espw_cri6n_u",
    "espw_spd6n2_u",
    "espw_spd6n3_u",
    "espw_spd6n_u",
    -> R.drawable.e7_item_icon_eq_neck_bone007
    "espw6r",
    "espw_ac6r",
    "espw_cri6r",
    "espw_spd6r",
    "espw_spd6r2",
    "espw_spd6r3",
    "espw_spd6r4",
    -> R.drawable.e7_item_icon_eq_ring_bone106
    "espw6r_u",
    "espw_ac6r_u",
    "espw_cri6r_u",
    "espw_spd6r2_u",
    "espw_spd6r3_u",
    "espw_spd6r4_u",
    "espw_spd6r_u",
    -> R.drawable.e7_item_icon_eq_ring_bone107
    "espw6w",
    "espw_ac6w",
    "espw_cri6w",
    "espw_spd6w",
    "espw_spd6w2",
    -> R.drawable.e7_item_icon_eq_weapon_bone006
    "espw6w_u",
    "espw_ac6w_u",
    "espw_cri6w_u",
    "espw_spd6w2_u",
    "espw_spd6w_u",
    -> R.drawable.e7_item_icon_eq_weapon_bone007
    else -> null
}

@DrawableRes
private fun gearItemIcon_ess1(code: String): Int? = when (code) {
    "ess12n",
    -> R.drawable.e7_item_icon_eq_neck_substory012
    "ess13n",
    -> R.drawable.e7_item_icon_eq_neck_substory013
    "ess14n",
    -> R.drawable.e7_item_icon_eq_neck_substory014
    "ess11r",
    -> R.drawable.e7_item_icon_eq_ring_substory011
    "ess15r",
    -> R.drawable.e7_item_icon_eq_ring_substory015
    "ess16w",
    -> R.drawable.e7_item_icon_eq_weapon_substory016
    "ess17w",
    -> R.drawable.e7_item_icon_eq_weapon_substory017
    "ess18w",
    -> R.drawable.e7_item_icon_eq_weapon_substory018
    "ess19w",
    -> R.drawable.e7_item_icon_eq_weapon_substory019
    else -> null
}

@DrawableRes
private fun gearItemIcon_ete1(code: String): Int? = when (code) {
    "ete1a",
    -> R.drawable.e7_item_icon_eq_armor_intelpack001
    "ete1b",
    -> R.drawable.e7_item_icon_eq_boot_intelpack001
    "ete1h",
    -> R.drawable.e7_item_icon_eq_helm_intelpack001
    "ete1n",
    -> R.drawable.e7_item_icon_eq_neck_intelpack001
    "ete1r",
    -> R.drawable.e7_item_icon_eq_ring_intelpack001
    "ete1w",
    -> R.drawable.e7_item_icon_eq_weapon_intelpack001
    else -> null
}

@DrawableRes
private fun gearItemIcon_ewb3(code: String): Int? = when (code) {
    "ewb3a",
    -> R.drawable.e7_item_icon_eq_armor_webevent003
    "ewb3b",
    -> R.drawable.e7_item_icon_eq_boot_webevent003
    "ewb3h",
    -> R.drawable.e7_item_icon_eq_helm_webevent003
    "ewb3n",
    -> R.drawable.e7_item_icon_eq_neck_webevent003
    "ewb3r",
    -> R.drawable.e7_item_icon_eq_ring_webevent003
    "ewb3w",
    -> R.drawable.e7_item_icon_eq_weapon_webevent003
    else -> null
}

@DrawableRes
private fun gearItemIcon_ewc2(code: String): Int? = when (code) {
    "ewc25r",
    -> R.drawable.e7_item_icon_eq_ring_e7wc2025
    else -> null
}

@DrawableRes
private fun gearItemIcon_ezl1(code: String): Int? = when (code) {
    "ezl1_a",
    -> R.drawable.e7_item_icon_eq_armor_ugquest001
    "ezl1_b",
    -> R.drawable.e7_item_icon_eq_boot_ugquest001
    "ezl1_h",
    -> R.drawable.e7_item_icon_eq_helm_ugquest001
    "ezl1_n",
    -> R.drawable.e7_item_icon_eq_neck_ugquest001
    "ezl1_r",
    -> R.drawable.e7_item_icon_eq_ring_ugquest001
    "ezl1_w",
    -> R.drawable.e7_item_icon_eq_weapon_ugquest001
    else -> null
}

@DrawableRes
private fun gearItemIcon_ezl2(code: String): Int? = when (code) {
    "ezl2_b",
    -> R.drawable.e7_item_icon_eq_boot_event002
    "ezl2_n",
    -> R.drawable.e7_item_icon_eq_neck_event001
    else -> null
}

@DrawableRes
private fun gearItemIcon_ezl3(code: String): Int? = when (code) {
    "ezl3_a",
    -> R.drawable.e7_item_icon_eq_armor_cnevent001
    "ezl3_b",
    -> R.drawable.e7_item_icon_eq_boot_cnevent001
    "ezl3_h",
    -> R.drawable.e7_item_icon_eq_helm_cnevent001
    "ezl3_n",
    -> R.drawable.e7_item_icon_eq_neck_cnevent001
    "ezl3_r",
    -> R.drawable.e7_item_icon_eq_ring_cnevent001
    "ezl3_w",
    -> R.drawable.e7_item_icon_eq_weapon_cnevent001
    else -> null
}

@DrawableRes
private fun gearItemIcon_ezl4(code: String): Int? = when (code) {
    "ezl4_a",
    -> R.drawable.e7_item_icon_eq_armor_jpncele001
    "ezl4_b",
    -> R.drawable.e7_item_icon_eq_boot_jpncele001
    "ezl4_h",
    -> R.drawable.e7_item_icon_eq_helm_jpncele001
    "ezl4_n",
    -> R.drawable.e7_item_icon_eq_neck_orb005
    "ezl4_r",
    -> R.drawable.e7_item_icon_eq_ring_cidonia003
    "ezl4_w",
    -> R.drawable.e7_item_icon_eq_weapon_jpncele001
    else -> null
}

@DrawableRes
private fun gearItemIcon_ezl5(code: String): Int? = when (code) {
    "ezl5_a",
    -> R.drawable.e7_item_icon_eq_armor_zl2pack
    "ezl5_b",
    -> R.drawable.e7_item_icon_eq_boot_zl2pack
    "ezl5_h",
    -> R.drawable.e7_item_icon_eq_helm_zl2pack
    "ezl5_n",
    -> R.drawable.e7_item_icon_eq_neck_zl2pack
    "ezl5_r",
    -> R.drawable.e7_item_icon_eq_ring_zl2pack
    "ezl5_w",
    -> R.drawable.e7_item_icon_eq_weapon_zl2pack
    else -> null
}

@DrawableRes
private fun gearItemIcon_ezl8(code: String): Int? = when (code) {
    "ezl8_a",
    -> R.drawable.e7_item_icon_eq_armor_jpncele001
    "ezl8_b",
    -> R.drawable.e7_item_icon_eq_boot_jpncele001
    "ezl8_h",
    -> R.drawable.e7_item_icon_eq_helm_jpncele001
    "ezl8_n",
    -> R.drawable.e7_item_icon_eq_neck_orb005
    "ezl8_r",
    -> R.drawable.e7_item_icon_eq_ring_cidonia003
    "ezl8_w",
    -> R.drawable.e7_item_icon_eq_weapon_jpncele001
    else -> null
}

@DrawableRes
private fun gearItemIcon_ezl9(code: String): Int? = when (code) {
    "ezl9_a",
    -> R.drawable.e7_item_icon_eq_armor_ugquest001
    "ezl9_b",
    -> R.drawable.e7_item_icon_eq_boot_ugquest001
    "ezl9_h",
    -> R.drawable.e7_item_icon_eq_helm_ugquest001
    "ezl9_n",
    -> R.drawable.e7_item_icon_eq_neck_ugquest001
    "ezl9_r",
    -> R.drawable.e7_item_icon_eq_ring_ugquest001
    "ezl9_w",
    -> R.drawable.e7_item_icon_eq_weapon_ugquest001
    else -> null
}
