package com.e7orbit.ui.theme

import androidx.compose.ui.graphics.Color

internal val OrbitLightPrimary = Color(0xFF315DA8)
internal val OrbitLightOnPrimary = Color(0xFFFFFFFF)
internal val OrbitLightPrimaryContainer = Color(0xFFD9E2FF)
internal val OrbitLightOnPrimaryContainer = Color(0xFF0B2F66)
internal val OrbitLightSecondary = Color(0xFF575E71)
internal val OrbitLightOnSecondary = Color(0xFFFFFFFF)
internal val OrbitLightSecondaryContainer = Color(0xFFDCE2F9)
internal val OrbitLightOnSecondaryContainer = Color(0xFF2B3042)
internal val OrbitLightTertiary = Color(0xFF765A00)
internal val OrbitLightOnTertiary = Color(0xFFFFFFFF)
internal val OrbitLightTertiaryContainer = Color(0xFFFFE08B)
internal val OrbitLightOnTertiaryContainer = Color(0xFF251A00)
internal val OrbitLightBackground = Color(0xFFF8F9FF)
internal val OrbitLightOnBackground = Color(0xFF191B20)
internal val OrbitLightSurface = Color(0xFFF8F9FF)
internal val OrbitLightOnSurface = Color(0xFF191B20)
internal val OrbitLightSurfaceVariant = Color(0xFFE1E2EC)
internal val OrbitLightOnSurfaceVariant = Color(0xFF44464F)
internal val OrbitLightOutline = Color(0xFF757780)
internal val OrbitLightOutlineVariant = Color(0xFFC5C6D0)

internal val OrbitDarkPrimary = Color(0xFFADC6FF)
internal val OrbitDarkOnPrimary = Color(0xFF002E69)
internal val OrbitDarkPrimaryContainer = Color(0xFF174684)
internal val OrbitDarkOnPrimaryContainer = Color(0xFFD9E2FF)
internal val OrbitDarkSecondary = Color(0xFFBFC6DC)
internal val OrbitDarkOnSecondary = Color(0xFF293042)
internal val OrbitDarkSecondaryContainer = Color(0xFF3F4658)
internal val OrbitDarkOnSecondaryContainer = Color(0xFFDCE2F9)
internal val OrbitDarkTertiary = Color(0xFFE9C349)
internal val OrbitDarkOnTertiary = Color(0xFF3E2E00)
internal val OrbitDarkTertiaryContainer = Color(0xFF584400)
internal val OrbitDarkOnTertiaryContainer = Color(0xFFFFE08B)
internal val OrbitDarkBackground = Color(0xFF111318)
internal val OrbitDarkOnBackground = Color(0xFFE2E2E9)
internal val OrbitDarkSurface = Color(0xFF111318)
internal val OrbitDarkOnSurface = Color(0xFFE2E2E9)
internal val OrbitDarkSurfaceVariant = Color(0xFF44464F)
internal val OrbitDarkOnSurfaceVariant = Color(0xFFC5C6D0)
internal val OrbitDarkOutline = Color(0xFF8F909A)
internal val OrbitDarkOutlineVariant = Color(0xFF44464F)

val OrbitSuccess = Color(0xFF247A52)
val OrbitWarning = Color(0xFF8A5A00)
