package com.e7orbit.ui.theme

import androidx.compose.ui.graphics.Color

// Material Theme Builder: neutral monochrome light scheme.
internal val WhitePrimary = Color(0xFF1B1B1B)
internal val WhiteOnPrimary = Color(0xFFFFFFFF)
internal val WhitePrimaryContainer = Color(0xFFF0F0F0)
internal val WhiteOnPrimaryContainer = Color(0xFF1B1B1B)
internal val WhiteInversePrimary = Color(0xFFC7C7C7)
internal val WhiteSecondary = Color(0xFF4F4F4F)
internal val WhiteOnSecondary = Color(0xFFFFFFFF)
internal val WhiteSecondaryContainer = Color(0xFFF1F1F1)
internal val WhiteOnSecondaryContainer = Color(0xFF1C1C1C)
internal val WhiteTertiary = Color(0xFF3F3F3F)
internal val WhiteOnTertiary = Color(0xFFFFFFFF)
internal val WhiteTertiaryContainer = Color(0xFFEDEDED)
internal val WhiteOnTertiaryContainer = Color(0xFF1A1A1A)
internal val WhiteError = Color(0xFFBA1A1A)
internal val WhiteOnError = Color(0xFFFFFFFF)
internal val WhiteErrorContainer = Color(0xFFFFDAD6)
internal val WhiteOnErrorContainer = Color(0xFF410002)
internal val WhiteBackground = Color(0xFFFFFFFF)
internal val WhiteOnBackground = Color(0xFF1B1B1B)
internal val WhiteSurface = Color(0xFFFFFFFF)
internal val WhiteOnSurface = Color(0xFF1B1B1B)
internal val WhiteSurfaceVariant = Color(0xFFF3F3F3)
internal val WhiteOnSurfaceVariant = Color(0xFF5F5F5F)
internal val WhiteOutline = Color(0xFF767676)
internal val WhiteOutlineVariant = Color(0xFFDEDEDE)
internal val WhiteScrim = Color(0xFF000000)
internal val WhiteInverseSurface = Color(0xFF303030)
internal val WhiteInverseOnSurface = Color(0xFFF4F4F4)
internal val WhiteSurfaceDim = Color(0xFFE2E2E2)
internal val WhiteSurfaceBright = Color(0xFFFFFFFF)
internal val WhiteSurfaceContainerLowest = Color(0xFFFFFFFF)
internal val WhiteSurfaceContainerLow = Color(0xFFFAFAFA)
internal val WhiteSurfaceContainer = Color(0xFFF7F7F7)
internal val WhiteSurfaceContainerHigh = Color(0xFFF1F1F1)
internal val WhiteSurfaceContainerHighest = Color(0xFFEBEBEB)

val OrbitSuccess = Color(0xFF247A52)
val OrbitWarning = Color(0xFF8A5A00)
val OrbitArtifactHighlight = Color(0xFFC2410C)
