#!/usr/bin/env python3
"""Import Epic Seven gear icons and generate their Android resource mapping."""

from __future__ import annotations

import argparse
from collections import defaultdict
import json
from pathlib import Path
import re
import shutil


SLOT_PREFIXES = (
    "icon_eq_weapon_",
    "icon_eq_helm_",
    "icon_eq_helmet_",
    "icon_eq_armor_",
    "icon_eq_neck_",
    "icon_eq_ring_",
    "icon_eq_boot_",
)
SLOTS = ("weapon", "helm", "armor", "neck", "ring", "boot")
BACKGROUND_ASSETS = {
    "e7_item_bg01.png": "_itembg_equip_1.png",
    "e7_item_bg02.png": "_itembg_equip_2.png",
    "e7_item_bg03.png": "_itembg_equip_3.png",
    "e7_item_bg04.png": "_itembg_equip_4.png",
    "e7_item_bg05.png": "_itembg_equip_5.png",
    "e7_item_slot.png": "cm_item_slot_0.png",
}
ENHANCEMENT_ASSETS = {
    **{f"e7_enhance_e{digit}.png": f"game_eff_dmg_e{digit}.png" for digit in range(10)},
    "e7_enhance_plus.png": "game_eff_dmg_el.png",
}
FALLBACK_GEAR_ASSETS = {
    "e7_fallback_gear_weapon.png": "icon_eq_weapon_arena002.png",
    "e7_fallback_gear_helmet.png": "icon_eq_helm_arena002.png",
    "e7_fallback_gear_armor.png": "icon_eq_armor_arena002.png",
    "e7_fallback_gear_necklace.png": "icon_eq_neck_arena002.png",
    "e7_fallback_gear_ring.png": "icon_eq_ring_arena002.png",
    "e7_fallback_gear_boots.png": "icon_eq_boot_arena002.png",
}
STAT_ASSETS = {
    "e7_stat_attack.png": "icon_stat_att.png",
    "e7_stat_attack_percent.png": "icon_stat_att.png",
    "e7_stat_defense.png": "icon_stat_def.png",
    "e7_stat_defense_percent.png": "icon_stat_def.png",
    "e7_stat_health.png": "icon_stat_max_hp.png",
    "e7_stat_health_percent.png": "icon_stat_max_hp.png",
    "e7_stat_speed.png": "icon_stat_speed.png",
    "e7_stat_crit_chance.png": "icon_stat_cri.png",
    "e7_stat_crit_damage.png": "icon_stat_cri_dmg.png",
    "e7_stat_effectiveness.png": "icon_stat_acc.png",
    "e7_stat_resistance.png": "icon_stat_res.png",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--equip-export", type=Path, required=True, help="equip_item_zl_db.jsonl")
    parser.add_argument("--item-dir", type=Path, required=True, help="Extracted item image directory")
    parser.add_argument("--project-root", type=Path, default=Path(__file__).resolve().parents[1])
    return parser.parse_args()


def code_aliases(code: str) -> set[str]:
    aliases = {code}
    suffixes = (
        ("_craft_chaos_u", "_u"),
        ("_craft_chaos", ""),
        ("_craft_u", "_u"),
        ("_chaos_u", "_u"),
        ("_craft", ""),
        ("_chaos", ""),
    )
    for suffix, replacement in suffixes:
        if code.endswith(suffix):
            aliases.add(code[: -len(suffix)] + replacement)
    return aliases


def read_mappings(export_path: Path, item_dir: Path) -> tuple[dict[str, str], set[str]]:
    mappings: dict[str, str] = {}
    icons: set[str] = set()
    with export_path.open(encoding="utf-8") as stream:
        for line in stream:
            if not line.strip():
                continue
            row = json.loads(line)
            code = str(row.get("row_id") or "")
            columns = row.get("columns") or []
            icon = next(
                (
                    str(value)
                    for value in columns
                    if isinstance(value, str) and value.startswith(SLOT_PREFIXES)
                ),
                "",
            )
            if not code or not icon or not (item_dir / f"{icon}.png").is_file():
                continue
            icons.add(icon)
            for alias in code_aliases(code):
                previous = mappings.setdefault(alias, icon)
                if previous != icon:
                    raise ValueError(f"conflicting icon aliases for {alias}: {previous}, {icon}")
    return mappings, icons


def inferred_icon_names() -> set[str]:
    names = {
        *(f"icon_eq_{slot}_alchemi_001" for slot in SLOTS),
        *(f"icon_eq_{slot}_attpack003" for slot in SLOTS),
        *(f"icon_eq_{slot}_insect008" for slot in SLOTS),
        *(f"icon_eq_{slot}_webevent001" for slot in SLOTS),
    }
    for season in range(12, 17):
        for slot in SLOTS:
            names.add(f"icon_eq_{slot}_arena{season:03d}")
    return names


def resource_name(icon: str) -> str:
    return f"e7_item_{icon}"


def kotlin_identifier(value: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", value)


def generate_kotlin(mappings: dict[str, str]) -> str:
    groups: dict[str, dict[str, list[str]]] = defaultdict(lambda: defaultdict(list))
    for code, icon in sorted(mappings.items()):
        groups[code[:4]][icon].append(code)

    output = [
        "package com.e7orbit.ui",
        "",
        "import androidx.annotation.DrawableRes",
        "import com.e7orbit.R",
        "",
        "// Generated by tools/sync_gear_icons.py from equip_item_zl.db.",
        "@DrawableRes",
        "internal fun exactGearItemIconRes(code: String): Int? = when (code.take(4)) {",
    ]
    for prefix in sorted(groups):
        output.append(f'    "{prefix}" -> gearItemIcon_{kotlin_identifier(prefix)}(code)')
    output.extend(("    else -> null", "}", ""))

    for prefix in sorted(groups):
        output.extend(
            (
                "@DrawableRes",
                f"private fun gearItemIcon_{kotlin_identifier(prefix)}(code: String): Int? = when (code) {{",
            )
        )
        for icon, codes in sorted(groups[prefix].items()):
            for code in codes:
                output.append(f'    "{code}",')
            output.append(f"    -> R.drawable.{resource_name(icon)}")
        output.extend(("    else -> null", "}", ""))
    return "\n".join(output)


def main() -> None:
    arguments = parse_args()
    resource_dir = arguments.project_root / "app/src/main/res-gear-icons/drawable-nodpi"
    legacy_resource_dir = arguments.project_root / "app/src/main/res/drawable-nodpi"
    night_resource_dir = arguments.project_root / "app/src/main/res/drawable-night-nodpi"
    kotlin_path = (
        arguments.project_root
        / "app/src/main/java/com/e7orbit/ui/GearItemIconAssets.generated.kt"
    )
    resource_dir.mkdir(parents=True, exist_ok=True)
    legacy_resource_dir.mkdir(parents=True, exist_ok=True)
    night_resource_dir.mkdir(parents=True, exist_ok=True)
    kotlin_path.parent.mkdir(parents=True, exist_ok=True)

    mappings, icons = read_mappings(arguments.equip_export, arguments.item_dir)
    icons.update(
        icon
        for icon in inferred_icon_names()
        if (arguments.item_dir / f"{icon}.png").is_file()
    )

    for directory in (resource_dir, legacy_resource_dir):
        for old_icon in directory.glob("e7_item_icon_eq_*.png"):
            old_icon.unlink()
        for background in directory.glob("e7_item_bg*.png"):
            background.unlink()
        for enhancement in directory.glob("e7_enhance_*.png"):
            enhancement.unlink()
        for fallback in directory.glob("e7_fallback_gear_*.png"):
            fallback.unlink()
        (directory / "e7_item_slot.png").unlink(missing_ok=True)
    source_img_dir = arguments.item_dir.parent / "img"
    for destination_name, source_name in {**BACKGROUND_ASSETS, **ENHANCEMENT_ASSETS}.items():
        source = source_img_dir / source_name
        if not source.is_file():
            raise FileNotFoundError(source)
        shutil.copyfile(source, resource_dir / destination_name)
    for destination_name, source_name in FALLBACK_GEAR_ASSETS.items():
        source = arguments.item_dir / source_name
        if not source.is_file():
            raise FileNotFoundError(source)
        shutil.copyfile(source, resource_dir / destination_name)
    for destination_name, source_name in STAT_ASSETS.items():
        source = source_img_dir / source_name
        if not source.is_file():
            raise FileNotFoundError(source)
        for destination_dir in (legacy_resource_dir, night_resource_dir):
            shutil.copyfile(source, destination_dir / destination_name)
    for icon in sorted(icons):
        shutil.copyfile(
            arguments.item_dir / f"{icon}.png",
            resource_dir / f"{resource_name(icon)}.png",
        )
    kotlin_path.write_text(generate_kotlin(mappings), encoding="utf-8", newline="\n")

    print(f"Imported {len(icons)} gear icons")
    print(f"Generated {len(mappings)} code mappings at {kotlin_path}")


if __name__ == "__main__":
    main()
